Repository UBC-MDS/fml_doc_gen, pull requests merged in 2025-01, with the labels that each got.

#10 fix docstring format & pytest
  .github/workflows/ci-cd.yml
  README.md
  docs/Makefile
  docs/example.ipynb
  docs/make.bat
  environment.yml
  poetry.lock
  pyproject.toml
  src/fml/fml.py
  src/fml_doc_gen/__init__.py
  src/fml_doc_gen/fml_doc_gen.py
  tests/test_fml.py
  tests/test_fml_doc_gen.py
Labels: documentation

#13 add func dto
  src/fml_doc_gen/fml_doc_gen.py
  src/fml_doc_gen/func_dto.py
Labels: enhancement

#14 Ml2 dto
  src/fml_doc_gen/fml_doc_gen.py
  src/fml_doc_gen/generate_template.py
  src/fml_doc_gen/read_user_function.py
  src/fml_doc_gen/write_docstring_to_file.py
Labels: enhancement

#15 2.3: Finish generate_template.py
  src/fml_doc_gen/fml_doc_gen.py
  src/fml_doc_gen/generate_template.py
Labels: enhancement

#16 2.3: Add tests for `generate_template.py`
  src/fml_doc_gen/generate_template.py
  tests/test_generate_template.py
Labels: tests

#18 Draft PR: Fixing my mess
  src/fml_doc_gen/func_dto.py
  tests/test_generate_template.py
Labels: tests

#17 ** DO NOT MERGE ** Ml2 readfunc
  docs/example.ipynb
  src/fml_doc_gen/fml_doc_gen.py
  src/fml_doc_gen/func_dto.py
  src/fml_doc_gen/generate_template.py
  src/fml_doc_gen/read_user_function.py
  tests/test_generate_template.py
  tests/test_read_user_function.py
Labels: documentation, enhancement, tests

#20 2.4: Putting it all together + final integration test
  src/fml_doc_gen/fml_doc_gen.py
  src/fml_doc_gen/func_dto.py
  src/fml_doc_gen/generate_template.py
  src/fml_doc_gen/read_user_function.py
  src/fml_doc_gen/write_docstring_to_file.py
  tests/test_fml_doc_gen.py
  tests/test_generate_template.py
Labels: enhancement

#23 3.1: Add Package Documentation
  docs/doc.txt
  docs/doc_img.png
  docs/example.ipynb
  src/fml_doc_gen/fml_doc_gen.py
Labels: documentation

#28 Doc
  docs/doc_img.png
  docs/example.ipynb
Labels: enhancement

#29 Final Change: Fix Documentation
  README.md
  docs/conf.py
  poetry.lock
  pyproject.toml
Labels: documentation

#39 fix: quick typo fix for docs
  docs/example.ipynb
Labels: bug

#43 fix: changed GITHUB TOKEN to PAT => allows use of ruleset
  README.md
Labels: enhancement

#44 Address Feedback + Autogen Docstring
  README.md
  docs/doc.txt
  docs/example.ipynb
  poetry.lock
  pyproject.toml
  src/fml_doc_gen/autogen.py
  src/fml_doc_gen/fml_doc_gen.py
  src/fml_doc_gen/func_dto.py
  src/fml_doc_gen/read_user_function.py
  tests/test_autogen.py
  tests/test_fml_doc_gen.py
  tests/test_read_user_function.py
Labels: documentation, enhancement, tests, feature
